apiVersion: v1
kind: Secret
metadata:
  name: front-tls
  namespace: monitoring
type: Opaque  
data:
  tls.crt: {{crt}}
  tls.key: {{key}}
type: kubernetes.io/tls

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: front
  namespace: monitoring
  labels:
    app: front
spec:
  rules:
    - host: {{host}}
      http:
        paths:
          - backend:
              serviceName: front-service
              servicePort: http
            path: /
  tls:
    - hosts:
      - {{host}}
      secretName: front-tls

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: monitoring
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
        commit: '{{commit}}'
    spec:
      containers:
      - name: front
        image: k8s-monitoring-front
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: front
