---
apiVersion: v1
kind: Namespace
metadata:
   name: springbatch

---   
apiVersion: v1
kind: Secret
metadata:
  name: springbatch-tls
  namespace: springbatch
type: Opaque  
data:
  tls.crt: {{crt}}
  tls.key: {{key}}
type: kubernetes.io/tls

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: springbatch-ingress
  namespace: springbatch
  labels:
    app: app
spec:
  rules:
    - host: {{host}}
      http:
        paths:
          - backend:
              serviceName: springbatch-service
              servicePort: http
            path: /
  tls:
    - hosts:
      - {{host}}
      secretName: springbatch-tls

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: springbatch
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
        commit: '{{commit}}'
    spec:
      containers:
        - name: app
          image: medinvention/spring-batch:arm
          imagePullPolicy: Always
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysqlsecret
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysqlsecret
                  key: password
            - name: DB_URL
              value: mysql.springbatch.svc.cluster.local:3306/batch
            - name: DATA_PATH
              value: /app/
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 3
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 300
            timeoutSeconds: 5
            periodSeconds: 60
            failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: springbatch-service
  namespace: springbatch
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: app