- hosts: all
  become: yes

  tasks:
    - name: Change password
      user:
        name: pirate
        update_password: always
        password: "{{ newpassword|password_hash('sha512') }}"

# pip install passlib
# ansible-playbook -i hostfile change-password.yml --extra-vars newpassword=12345678